; SPDX-FileCopyrightText: 2023 Zeal 8-bit Computer <contact@zeal8bit.com>
;
; SPDX-License-Identifier: Apache-2.0

    IFNDEF ASSEMBLER_MACROS
    DEFINE ASSEMBLER_MACROS

    EXTERN memsep
    EXTERN strtolower
    EXTERN strltrim
    EXTERN strrtrim
    EXTERN strnltrim
    EXTERN strnrtrim
    EXTERN strsep
    EXTERN strcmp
    EXTERN strcpy
    EXTERN strlen
    EXTERN strncmp
    EXTERN strncmp_opt
    EXTERN parse_int
    EXTERN parse_str
    EXTERN is_digit
    EXTERN is_alpha_numeric
    EXTERN is_alpha
    EXTERN assemble_set_org
    EXTERN assemble_def_message
    EXTERN assemble_def_word
    EXTERN assemble_def_byte
    EXTERN assemble_def_space

    ; Maximum length for labels
    DEFC ASSEMBLE_MAX_LABEL_LENGTH = 16

    ; Each entry in _assemble_instructions_str has a size of 6 bytes
    ; 4 bytes for the instruction name and 2 bytes for the pointer
    ; which handles the instruction
    DEFC ASSEMBLE_INSTR_ENTRY_SIZE = 9

    DEFC ASSEMBLE_REGISTER_B = 0
    DEFC ASSEMBLE_REGISTER_C = 1
    DEFC ASSEMBLE_REGISTER_D = 2
    DEFC ASSEMBLE_REGISTER_E = 3
    DEFC ASSEMBLE_REGISTER_H = 4
    DEFC ASSEMBLE_REGISTER_L = 5
    DEFC ASSEMBLE_REGISTER_A = 7
    DEFC ASSEMBLE_REGISTER_I = 8
    DEFC ASSEMBLE_REGISTER_R = 9
    DEFC ASSEMBLE_LABEL_NAME = 10
    DEFC ASSEMBLE_CONSTANT_N = 15
    ; Number of 8-bit registers
    DEFC ASSEMBLE_REGISTER_MAX = 10
    ; Special 8-bit registers start
    DEFC ASSEMBLE_REGISTER_SPECIAL = ASSEMBLE_REGISTER_I

    DEFC ASSEMBLE_REG16_MASK   = 0x10
    DEFC ASSEMBLE_REG16_BIT    = 4
    DEFC ASSEMBLE_REGISTER_BC  = 0 | ASSEMBLE_REG16_MASK
    DEFC ASSEMBLE_REGISTER_DE  = 1 | ASSEMBLE_REG16_MASK
    DEFC ASSEMBLE_REGISTER_HL  = 2 | ASSEMBLE_REG16_MASK
    DEFC ASSEMBLE_REGISTER_SP  = 3 | ASSEMBLE_REG16_MASK
    DEFC ASSEMBLE_REGISTER_IX  = 4 | ASSEMBLE_REG16_MASK
    DEFC ASSEMBLE_REGISTER_IY  = 5 | ASSEMBLE_REG16_MASK
    DEFC ASSEMBLE_REGISTER_AFp = 6 | ASSEMBLE_REG16_MASK
    ; AF register shall ALWAYS be set to a value that has 0b11 as
    ; its lowest two bits
    DEFC ASSEMBLE_REGISTER_AF  = 7 | ASSEMBLE_REG16_MASK

    DEFC ASSEMBLE_MEMACC_MASK = 0x20
    DEFC ASSEMBLE_MEMACC_BIT  = 5
    DEFC ASSEMBLE_REGISTER_MEMBC  = 0 | ASSEMBLE_MEMACC_MASK
    DEFC ASSEMBLE_REGISTER_MEMDE  = 1 | ASSEMBLE_MEMACC_MASK
    DEFC ASSEMBLE_REGISTER_MEMHL  = 2 | ASSEMBLE_MEMACC_MASK
    DEFC ASSEMBLE_REGISTER_MEMSP  = 3 | ASSEMBLE_MEMACC_MASK
    DEFC ASSEMBLE_REGISTER_MEMIX  = 4 | ASSEMBLE_MEMACC_MASK
    DEFC ASSEMBLE_REGISTER_MEMIY  = 5 | ASSEMBLE_MEMACC_MASK
    DEFC ASSEMBLE_REGISTER_MEMNN  = 8 | ASSEMBLE_MEMACC_MASK
    DEFC ASSEMBLE_REGISTER_MEMC   = 9 | ASSEMBLE_MEMACC_MASK

    DEFC ASSEMBLE_FLAG_MASK = 0x40
    DEFC ASSEMBLE_FLAG_BIT  = 6
    DEFC ASSEMBLE_FLAG_NZ = 0 | ASSEMBLE_FLAG_MASK
    DEFC ASSEMBLE_FLAG_Z  = 1 | ASSEMBLE_FLAG_MASK
    DEFC ASSEMBLE_FLAG_NC = 2 | ASSEMBLE_FLAG_MASK
    DEFC ASSEMBLE_FLAG_C  = 3 | ASSEMBLE_FLAG_MASK
    DEFC ASSEMBLE_FLAG_PO = 4 | ASSEMBLE_FLAG_MASK
    DEFC ASSEMBLE_FLAG_PE = 5 | ASSEMBLE_FLAG_MASK
    DEFC ASSEMBLE_FLAG_P  = 6 | ASSEMBLE_FLAG_MASK
    DEFC ASSEMBLE_FLAG_M  = 7 | ASSEMBLE_FLAG_MASK

    DEFC ASSEMBLE_ERROR             = 0x80
    DEFC ASSEMBLE_UNKNOWN_OPERAND   = 0x80
    DEFC ASSEMBLE_INVALID_OPERAND   = 0x81
    DEFC ASSEMBLE_SYNTAX_ERROR      = 0x82
    DEFC ASSEMBLE_OUT_OF_RANGE      = 0x83
    DEFC ASSEMBLE_LABEL_TOO_LONG    = 0x84
    DEFC ASSEMBLE_ORG_ALREADY_SET   = 0x85
    DEFC ASSEMBLE_UNKNOWN_DIRECTIVE = 0x86

    ENDIF